###############################################################################
#
# Local source generation targets.
#
###############################################################################

ucli:
	$(SUBMODULE_BIGCODE)/tools/uclihandlers.py x86_64_stordis_bf2556x_1t_ucli.c

